import logging

from postgrest.exceptions import APIError

from app.services.supabase.factory import get_supabase_client

logger = logging.getLogger(__name__)


def get_or_create_workflow_run(workflow_run_id: str, patient_id: str, current_step: str = "coordinator") -> dict:
    """Return the conversation's workflow_run, creating it once if it doesn't exist.

    A conversation has ONE workflow_run, shared across every request/step in
    that conversation (its id is the conversation id, generated by the frontend
    and used as both the workflow_run id and the checkpointer thread_id). The
    Coordinator calls this on every request: it creates the row on the first
    message of a conversation and simply returns the existing one thereafter.

    Args:
        workflow_run_id: The conversation id — used as this row's id.
        patient_id: The patient_profiles.id this conversation belongs to.
        current_step: The step to record if the row is being created now.

    Returns:
        The workflow_runs row (existing or newly created).

    Raises:
        RuntimeError: If the lookup or insert fails.
    """
    client = get_supabase_client()
    try:
        existing = (
            client.table("workflow_runs").select("*").eq("id", workflow_run_id).execute()
        )
        if existing.data:
            return existing.data[0]
        response = client.table("workflow_runs").insert({
            "id": workflow_run_id,
            "patient_id": patient_id,
            "current_step": current_step,
            "state": {},
            "status": "in_progress",
        }).execute()
    except APIError as e:
        logger.error(f"Failed to get/create workflow_run {workflow_run_id}: {e}")
        raise RuntimeError(f"Failed to get/create workflow_run: {e}") from e
    return response.data[0]


def update_workflow_run(workflow_run_id: str, current_step: str, state: dict, status: str = "in_progress") -> dict:
    """Update an existing workflow_runs row's progress.

    Use this after every node runs. The given `state` is MERGED into whatever is
    already stored (not replaced), so each node's contribution accumulates — e.g.
    the Coordinator's `summary` survives even after later nodes add their own
    fields. Pass only the fields this step is adding/changing.

    Args:
        workflow_run_id: The workflow_runs.id to update.
        current_step: The name of the node that just ran, e.g. "routing".
        state: The fields this step wants to add/update; merged into the
            existing state.
        status: One of "in_progress", "completed", "failed", "escalated", "blocked".
            Defaults to "in_progress".

    Returns:
        The updated workflow_runs row as a dict.

    Raises:
        RuntimeError: If the update fails, or no workflow_run with that id exists.
    """
    client = get_supabase_client()
    try:
        existing = client.table("workflow_runs").select("state").eq("id", workflow_run_id).execute()
        current_state = existing.data[0]["state"] if existing.data else {}
        merged_state = {**(current_state or {}), **state}  # accumulate, don't clobber
        response = (
            client.table("workflow_runs")
            .update({"current_step": current_step, "state": merged_state, "status": status})
            .eq("id", workflow_run_id)
            .execute()
        )
    except APIError as e:
        logger.error(f"Failed to update workflow_run {workflow_run_id}: {e}")
        raise RuntimeError(f"Failed to update workflow_run: {e}") from e
    if not response.data:
        raise RuntimeError(f"No workflow_run found with id {workflow_run_id}")
    return response.data[0]
